# Generated by Django 2.0.1 on 2018-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('submitted_at', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('owner', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
