# Generated by Django 2.0.1 on 2018-01-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180125_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Collaborator',
        ),
    ]
