# Generated by Django 2.0.2 on 2018-02-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_auto_20180125_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Text')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='By')),
            ],
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.AlterField(
            model_name='job',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Collaborators will be able to check and update the request and download the data. Currently, only individuals with a U-M account may be added as collaborators.', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(help_text='Provide a brief description of your request and any important notes for the review team.', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(help_text='Submit a ZIP file containing your code, a dockerfile, and README file. See Getting Started for more information.', upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='job',
            name='filename',
            field=models.CharField(max_length=64, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='Write a short, descriptive title that will help you identify this request.', max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.CharField(max_length=64, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=django_fsm.FSMField(default='PENDING_CODE_REVIEW', editable=False, max_length=50, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='submitted_at',
            field=models.DateTimeField(verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.Job', verbose_name='Job'),
        ),
    ]
