# Generated by Django 2.0.2 on 2018-02-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180208_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='job',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Collaborators will be able to check and update the request and download the data. Currently, only individuals with a U-M account may be added as collaborators.', related_name='collaborating', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators'),
        ),
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
    ]
