# Generated by Django 2.0.2 on 2018-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180212_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Output'),
        ),
    ]
