# Generated by Django 2.0.2 on 2018-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.FileField(blank=True, upload_to='', verbose_name='Output'),
        ),
    ]
