# Generated by Django 2.0.3 on 2018-03-19 13:59

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20180219_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='Failed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=django_fsm.FSMField(default='PENDING_CODE_REVIEW', editable=False, max_length=50, verbose_name='Status'),
        ),
    ]
