# Generated by Django 2.0.3 on 2018-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180319_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='errors',
            field=models.FileField(blank=True, upload_to='', verbose_name='Errors'),
        ),
    ]
