version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  portal:
    build: ./portal
    environment:
      - 'ADMINS=${ADMINS}'
      - 'ALLOWED_HOSTS=*'
      - 'DATABASE_URL=postgresql://postgres@db/postgres'
      - 'DEBUG=${DEBUG}'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}'
      - 'PRIVATE_JOB_OUTPUT_ROOT=${PRIVATE_JOB_OUTPUT_ROOT}'
      - 'PRIVATE_STORAGE_ROOT=${PRIVATE_STORAGE_ROOT}'
      - 'JOB_ENV_VARS=${JOB_ENV_VARS}'
      - 'JOB_ENV_FILE=${JOB_ENV_FILE}'
      - 'JOB_CONTAINER_MEM_LIMIT=${JOB_CONTAINER_MEM_LIMIT}'
      - 'JOB_CONTAINER_MEMSWAP_LIMIT=${JOB_CONTAINER_MEMSWAP_LIMIT}'
      - 'JOB_CONTAINER_VOLUME_MOUNT=${JOB_CONTAINER_VOLUME_MOUNT}'
      - 'SAML2_ENTITY_ID=${SAML2_ENTITY_ID}'
      - 'SAML2_SP_CERT=${SAML2_SP_CERT}'
      - 'SAML2_SP_KEY=${SAML2_SP_KEY}'
      - 'SAML2_IDP_METADATA=${SAML2_IDP_METADATA}'
      - 'SAML2_SP_NAME=${SAML2_SP_NAME}'
      - 'SAML2_LS_REDIRECT=${SAML2_LS_REDIRECT}'
      - 'SAML2_LS_POST=${SAML2_LS_POST}'
      - 'SAML2_ACS_POST=${SAML2_ACS_POST}'
      - 'SAML2_REQUIRED_ATTRIBUTES=${SAML2_REQUIRED_ATTRIBUTES}'
      - 'SAML2_OPTIONAL_ATTRIBUTES=${SAML2_OPTIONAL_ATTRIBUTES}'
      - 'SECRET_KEY_PORTAL=${SECRET_KEY_PORTAL}'
      - 'SERVER_EMAIL=${SERVER_EMAIL}'
      - 'EMAIL_HOST=${EMAIL_HOST}'
      - 'EMAIL_HOST_USER=${EMAIL_HOST_USER}'
      - 'EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}'
      - 'EMAIL_PORT=${EMAIL_PORT}'
      - 'EMAIL_USE_TLS=${EMAIL_USE_TLS}'
      - 'ABSOLUTE_URL_BASE=${ABSOLUTE_URL_BASE}'
      - 'RUNNER_QUEUE_USER=${RUNNER_QUEUE_USER}'
      - 'RUNNER_QUEUE_PASS=${RUNNER_QUEUE_PASS}'
      - 'DOCKER_HOST=tcp://runner-docker-daemon:2375'
      - 'DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}'
      - 'DOCKER_TLSCACERT=${DOCKER_TLSCACERT}'
      - 'DOCKER_CLIENT_TLSCERT=${DOCKER_CLIENT_TLSCERT}'
      - 'DOCKER_CLIENT_TLSKEY=${DOCKER_CLIENT_TLSKEY}'
      - 'ADDITIONAL_INSTALLED_APPS=${ADDITIONAL_INSTALLED_APPS}'
      - 'INSTALLED_APPS_ENV_VARS=${INSTALLED_APPS_ENV_VARS}'
      - 'RESTRICTED_ACCESS_GROUPS=${RESTRICTED_ACCESS_GROUPS}'
    command: python3.6 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./portal:/usr/src/app
    ports:
      - "8023:8000"
    depends_on:
      - db
      - runner-worker
  rabbit:
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=${RUNNER_QUEUE_USER}
        - RABBITMQ_DEFAULT_PASS=${RUNNER_QUEUE_PASS}
    ports:
        - "5673:5672"
  runner-docker-daemon:
    build: ./runner-docker-daemon
    privileged: true
    environment:
      - 'JOB_RESOURCES=${JOB_RESOURCES}'
      - 'DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}'
      - 'DOCKER_TLSCACERT=${DOCKER_TLSCACERT}'
      - 'DOCKER_SERVER_TLSCERT=${DOCKER_SERVER_TLSCERT}'
      - 'DOCKER_SERVER_TLSKEY=${DOCKER_SERVER_TLSKEY}'
      - 'DOCKER_CLIENT_TLSCERT=${DOCKER_CLIENT_TLSCERT}'
      - 'DOCKER_CLIENT_TLSKEY=${DOCKER_CLIENT_TLSKEY}'
    volumes:
      - ./runner-docker-daemon:/usr/src/app
  runner-worker:
    build: ./portal
    environment:
      - 'ADMINS=${ADMINS}'
      - 'DATABASE_URL=postgresql://postgres@db/postgres'
      - 'DEBUG=${DEBUG}'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}'
      - 'PRIVATE_JOB_OUTPUT_ROOT=${PRIVATE_JOB_OUTPUT_ROOT}'
      - 'PRIVATE_STORAGE_ROOT=${PRIVATE_STORAGE_ROOT}'
      - 'JOB_ENV_VARS=${JOB_ENV_VARS}'
      - 'JOB_ENV_FILE=${JOB_ENV_FILE}'
      - 'JOB_CONTAINER_MEM_LIMIT=${JOB_CONTAINER_MEM_LIMIT}'
      - 'JOB_CONTAINER_MEMSWAP_LIMIT=${JOB_CONTAINER_MEMSWAP_LIMIT}'
      - 'JOB_CONTAINER_CPU_PERIOD=${JOB_CONTAINER_CPU_PERIOD}'
      - 'JOB_CONTAINER_CPU_QUOTA=${JOB_CONTAINER_CPU_QUOTA}'
      - 'JOB_CONTAINER_VOLUME_MOUNT=${JOB_CONTAINER_VOLUME_MOUNT}'
      - 'SAML2_ENTITY_ID=${SAML2_ENTITY_ID}'
      - 'SAML2_SP_CERT=${SAML2_SP_CERT}'
      - 'SAML2_SP_KEY=${SAML2_SP_KEY}'
      - 'SAML2_IDP_METADATA=${SAML2_IDP_METADATA}'
      - 'SAML2_SP_NAME=${SAML2_SP_NAME}'
      - 'SAML2_LS_REDIRECT=${SAML2_LS_REDIRECT}'
      - 'SAML2_LS_POST=${SAML2_LS_POST}'
      - 'SAML2_ACS_POST=${SAML2_ACS_POST}'
      - 'SAML2_REQUIRED_ATTRIBUTES=${SAML2_REQUIRED_ATTRIBUTES}'
      - 'SAML2_OPTIONAL_ATTRIBUTES=${SAML2_OPTIONAL_ATTRIBUTES}'
      - 'SECRET_KEY_PORTAL=${SECRET_KEY_PORTAL}'
      - 'EMAIL_HOST=${EMAIL_HOST}'
      - 'EMAIL_HOST_USER=${EMAIL_HOST_USER}'
      - 'EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}'
      - 'EMAIL_PORT=${EMAIL_PORT}'
      - 'EMAIL_USE_TLS=${EMAIL_USE_TLS}'
      - 'ABSOLUTE_URL_BASE=${ABSOLUTE_URL_BASE}'
      - 'RUNNER_QUEUE_USER=${RUNNER_QUEUE_USER}'
      - 'RUNNER_QUEUE_PASS=${RUNNER_QUEUE_PASS}'
      - 'DOCKER_HOST=tcp://runner-docker-daemon:2375'
      - 'DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}'
      - 'DOCKER_TLSCACERT=${DOCKER_TLSCACERT}'
      - 'DOCKER_CLIENT_TLSCERT=${DOCKER_CLIENT_TLSCERT}'
      - 'DOCKER_CLIENT_TLSKEY=${DOCKER_CLIENT_TLSKEY}'
    command: celery -A jobs worker --loglevel=${RUNNER_WORKER_LOGLEVEL}
    volumes:
      - ./portal:/usr/src/app
    depends_on:
      - runner-docker-daemon
      - rabbit
