apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: job-files
  name: job-files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: $JOB_FILES_STORAGE
status: {}
