FROM python:3

# Prereqs for PySAML
RUN apt-get update
RUN apt-get install xmlsec1 libffi-dev libssl-dev

ENV PYTHONUNBUFFERED 1

EXPOSE 8000

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN pip install psycopg2 gunicorn

COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

COPY . /usr/src/app/

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "privascope_web:app"]
